name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Run Coverage
        run: mvn -B test -f pom.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Fail if coverage is below 60%
        run: |
          coverage=$(grep -oP 'total="[^"]"\s+covered="\K[^"]' target/site/jacoco/jacoco.xml)
          echo "Code coverage: $coverage%"
          if (( $(echo "$coverage < 60" | bc -l) )); then
            echo "Code coverage is less than 60%, failing build"
            exit 1
          fi